# Generated by Django 3.1.2 on 2020-11-15 02:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loradata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loradata',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
