# Generated by Django 3.1.2 on 2020-11-15 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loradata', '0002_loradata_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='loradata',
            name='key',
            field=models.CharField(default='ASIA', max_length=100),
        ),
        migrations.AddField(
            model_name='loradata',
            name='latitude',
            field=models.CharField(default='36.35111', max_length=100),
        ),
        migrations.AddField(
            model_name='loradata',
            name='longitude',
            field=models.CharField(default='127.38500', max_length=100),
        ),
        migrations.AddField(
            model_name='loradata',
            name='name',
            field=models.CharField(default='Daejeon', max_length=100),
        ),
    ]
